Fix syntax error
Using `'` instead of `"` here caused a problem because of string interpolation

```
kevin@MacBookPro in kuna_server/ on main
› python3 kuna_server.py  <redacted>
  File "/Users/kevin/dev/kuna_server/kuna_server.py", line 208
    self.log.info(f'Client: start listening for camera: {camera['id']} ({camera['name']}) on {host}:{port}')
                                                                 ^^
SyntaxError: f-string: unmatched '['
(kuna_server) FAIL: 1
```